apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}-serving-cert
  namespace: {{ .Values.namespace }}
spec:
  dnsNames:
  - {{ .Values.name }}-webhook-service.{{ .Values.namespace }}.svc
  - {{ .Values.name }}-webhook-service.{{ .Values.namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ .Values.name }}-selfsigned-issuer
  secretName: webhook-server-cert