apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}-leader-election-rolebinding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.name }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}-controller-manager
  namespace: {{ .Values.namespace }}