apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.name }}/{{ .Values.name }}-serving-cert
  name: {{ .Values.name }}-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.name }}-webhook-service
      namespace: {{ .Values.namespace }}
      path: /validate-kube-green-com-v1alpha1-sleepinfo
  failurePolicy: Fail
  name: vsleepinfo.kb.io
  rules:
  - apiGroups:
    - kube-green.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sleepinfos
  sideEffects: None